#!/usr/bin/env node
/**
 * Power / Threat / Fear assessments from data/power/<batch>.json, checked against the research they cite,
 * written to js/power-assessments.js for the site (js/scaling.js merges them over its hand-written entries).
 *
 * Each file maps a slug to:
 *   { "power": "divine" | null, "threat": "t4" | null, "fear": "f3" | null,
 *     "reasons": { "power": { "id": "...", "en": "...", "claim_ids": ["<slug>-c03"] }, "threat": {...}, "fear": {...} },
 *     "oleh": "claude-cloud", "tanggal": "YYYY-MM-DD" }
 * A level must cite at least one claim of the creature's current accepted research; null means "not assessed"
 * and still needs a bilingual reason. A missing basis is never turned into a low level.
 *
 * An entry may also carry "perlu_riset": what the research lacks for a fair assessment (powers, domain, deeds,
 * scale). An entry with only "perlu_riset" and no levels is listed for a later power-focused enrichment and
 * is not published.
 *
 *   node scripts/build-power.mjs            check and write js/power-assessments.js
 *   node scripts/build-power.mjs --check    check only; fail if js/power-assessments.js is out of date
 *   node scripts/build-power.mjs --validate check data/power/ only; never writes or compares the generated file
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { computeFillStatus } from './gemini/fill-lib.mjs';
import { SCALES } from '../js/scaling.js';

const ROOT = new URL('../', import.meta.url);
const CHECK = process.argv.includes('--check');
const VALIDATE = process.argv.includes('--validate');
const OUT = new URL('js/power-assessments.js', ROOT);
const AXES = Object.keys(SCALES);
const text = v => typeof v === 'string' && v.trim().length >= 20;

const creatures = JSON.parse(await readFile(new URL('data/creatures.json', ROOT), 'utf8'));
const { status, entries } = await computeFillStatus(creatures);
const errors = [];
const out = {};
const needsResearch = [];
const files = (await readdir(new URL('data/power/', ROOT)).catch(() => [])).filter(n => /^batch-\d+\.json$/.test(n)).sort();
for (const name of files) {
  const batch = name.slice(0, -5);
  const data = JSON.parse(await readFile(new URL(`data/power/${name}`, ROOT), 'utf8'));
  for (const [slug, a] of Object.entries(data)) {
    const where = `${name} ${slug}`;
    if (status[slug]?.batch !== batch) { errors.push(`${where}: slug ini tidak ada di ${batch}`); continue; }
    const research = entries.get(slug);
    if (!research) { errors.push(`${where}: belum punya riset yang valid`); continue; }
    if (a.perlu_riset !== undefined && !text(a.perlu_riset)) errors.push(`${where}: perlu_riset harus menjelaskan apa yang kurang (minimal 20 karakter)`);
    if (a.perlu_riset) needsResearch.push(slug);
    if (AXES.every(axis => a[axis] == null) && a.perlu_riset) continue;
    const claimIds = new Set(research.claims.map(c => c.id));
    for (const axis of AXES) {
      const level = a[axis];
      if (level !== null && !SCALES[axis].some(l => l.id === level)) errors.push(`${where}: ${axis} "${level}" tidak dikenal`);
      const reason = a.reasons?.[axis];
      if (!text(reason?.id) || !text(reason?.en)) errors.push(`${where}: alasan ${axis} harus dwibahasa (id dan en, minimal 20 karakter)`);
      const cited = reason?.claim_ids || [];
      if (level !== null && !cited.length) errors.push(`${where}: ${axis} "${level}" harus merujuk minimal satu klaim`);
      for (const id of cited) if (!claimIds.has(id)) errors.push(`${where}: ${axis} merujuk klaim yang tidak ada di riset sekarang (${id})`);
    }
    if (AXES.every(axis => a[axis] === null)) errors.push(`${where}: ketiga sumbu null; jangan simpan entri tanpa penilaian`);
    out[slug] = {
      power: a.power, threat: a.threat, fear: a.fear,
      reasons: Object.fromEntries(AXES.map(axis => [axis, { id: a.reasons[axis].id, en: a.reasons[axis].en, claim_ids: a.reasons[axis].claim_ids || [] }])),
    };
  }
}
if (errors.length) {
  console.error(`${errors.length} masalah:\n${errors.map(e => `  - ${e}`).join('\n')}`);
  process.exit(1);
}

const sorted = Object.fromEntries(Object.keys(out).sort().map(k => [k, out[k]]));
const js = `// Generated by scripts/build-power.mjs from data/power/*.json. Do not edit by hand.\n// Every level cites claims of the creature's accepted research; see the claim_ids of each reason.\nexport const POWER_ASSESSMENTS = Object.freeze(${JSON.stringify(sorted, null, 2)});\n`;
const current = await readFile(OUT, 'utf8').catch(() => '');
if (VALIDATE) {
  console.log(`Data penilaian valid: ${Object.keys(sorted).length} makhluk dari ${files.length} berkas; ${needsResearch.length} ditandai perlu riset kekuatan.`);
} else if (CHECK) {
  if (current !== js) {
    console.error('js/power-assessments.js tidak sesuai data/power/. Jalankan: node scripts/build-power.mjs');
    process.exit(1);
  }
  console.log(`Penilaian kekuatan valid: ${Object.keys(sorted).length} makhluk dari ${files.length} berkas; ${needsResearch.length} ditandai perlu riset kekuatan.`);
} else {
  if (current !== js) await writeFile(OUT, js);
  console.log(`js/power-assessments.js: ${Object.keys(sorted).length} makhluk dari ${files.length} berkas; ${needsResearch.length} ditandai perlu riset kekuatan.`);
}
